import { COMPOUND_MAP } from './maps/compound'
import type { MapModule, MissionDef } from './types'

/**
 * The rescue campaign, in order: finishing a mission opens the next. Each is longer and harder than the last,
 * with more stages spread over more of the map. Everything a mission names is an anchor on its map
 * (maps/compound.ts); a mission on a new map only needs that map's anchors.
 */
export const MAPS: Record<string, MapModule> = { compound: COMPOUND_MAP }

export const MISSIONS: MissionDef[] = [
  {
    id: 'safe-return', number: 1, name: 'Safe Return', estimate: '20 to 30 minutes', map: 'compound',
    briefing: 'Tomas Vell, a rail engineer, is held somewhere under the detention block in the east annex. Get in past the mess hall, blind the cameras, find his cell and drive him out through the east gate.',
    spawns: ['north-road'], cells: ['detention-1', 'detention-2', 'detention-3', 'detention-4'], hostages: 1, hostageName: 'Tomas',
    extraction: 'east-jeep',
    cameras: ['detention-camera', 'jeep-camera', 'security-camera', 'mess-hall-exit-camera', 'rail-pole-camera'],
    panels: ['ammo-yard', 'ammo-annex'], lockedDoors: [], keycards: [], boosts: ['rail-fence', 'annex-fence'],
    guards: ['world', 'reserve-extra-1', 'reserve-extra-2', 'reserve-extra-3', 'reserve-extra-4', 'annex-rail-watch', 'detention-yard', 'mess-yard-2', 'rail-yard-2', 'annex-night-1', 'annex-night-2', 'yard-night', 'warehouse-night'],
    dogs: [], alarmLocks: [],
    stages: [
      { id: 'in', title: 'Get inside', objectives: [{ id: 'reach-inside', kind: 'reach', zone: 'inside', text: 'Get into the compound: through the mess hall, or round by the west service gate' }] },
      { id: 'blind', title: 'Blind the cameras', objectives: [{ id: 'cameras', kind: 'use', panels: ['signals-office-computer', 'security-computer'], text: 'Shut the cameras down: the office terminal (60 s) or the security cabin (for good)' }] },
      { id: 'find', title: 'Find Tomas', objectives: [{ id: 'reach-annex', kind: 'reach', zone: 'detention', text: 'Reach the detention block in the east annex' }, { id: 'find', kind: 'find', text: 'Search the cells below the detention block' }] },
      { id: 'free', title: 'Free Tomas', objectives: [{ id: 'free', kind: 'free', text: 'Unlock his cell' }] },
      { id: 'escort', title: 'Get him out', objectives: [{ id: 'escort', kind: 'escort', text: 'Bring Tomas to the jeep by the east gate' }] },
      { id: 'out', title: 'Drive', objectives: [{ id: 'extract', kind: 'extract', text: 'Open the gate and drive out together' }] },
    ],
    par: { normal: 22 * 60, hard: 26 * 60, nightmare: 30 * 60 },
    tools: { pebbles: 4, charges: 1, drone: true },
  },
  {
    id: 'cold-storage', number: 2, name: 'Cold Storage', estimate: '25 to 35 minutes', map: 'compound',
    briefing: 'Mara Linde photographed the munitions wagon and never came back. She is held in one of the storage buildings. Cut the power, pull her location off the laptop in the administration wing, and call in a helicopter. Hold the landing zone until it touches down.',
    spawns: ['fuel-belt', 'north-road'], cells: ['warehouse-east', 'stores-southwest', 'shed-west'], hostages: 1, hostageName: 'Mara',
    extraction: 'north-yard-heli',
    cameras: ['mess-hall-exit-camera', 'yard-pole-camera', 'west-shed-camera', 'stores-pole-camera', 'loading-pole-camera', 'admin-pole-camera', 'rail-pole-camera'],
    panels: ['fuse-west', 'intel-admin', 'ammo-yard', 'ammo-court', 'medkit-west', 'card-gatehouse', 'card-mess'],
    lockedDoors: [
      { door: 'Southwest stores · entry 2', lock: 'pick', label: 'the stores' },
      { door: 'Southwest stores · entry 1', lock: 'keycard', card: 'stores-card', label: 'the stores' },
      { door: 'West equipment shed A · entry 1', lock: 'pick', label: 'the shed' },
      { door: 'West administration wing · entry 1', lock: 'keycard', card: 'stores-card', label: 'the administration wing' },
    ],
    keycards: [{ id: 'stores-card', label: 'the stores keycard', at: ['card-gatehouse', 'card-mess'] }],
    boosts: ['rail-fence', 'inner-fence'],
    guards: ['world', 'reserve-extra-1', 'reserve-extra-2', 'reserve-extra-3', 'reserve-extra-4', 'warehouse-stores', 'warehouse-rear', 'stores-yard', 'stores-inside', 'shed-watch', 'west-fence', 'gatehouse-yard', 'admin-inside',
      'court-patrol', 'court-night', 'yard-lz', 'mess-yard-2', 'yard-night', 'west-night', 'mess-roof-sniper', 'warehouse-night'],
    dogs: ['dog-yard', 'dog-stores'], alarmLocks: ['West administration wing · entry 1'],
    stages: [
      { id: 'dark', title: 'Kill the lights', objectives: [{ id: 'power', kind: 'use', panels: ['fuse-west'], text: 'Cut the power at the fuse box by the west utility building' }] },
      { id: 'intel', title: 'Where is she?', objectives: [{ id: 'card', kind: 'use', panels: ['card-gatehouse', 'card-mess'], text: 'Find the keycard for the administration wing', optional: true }, { id: 'intel', kind: 'use', panels: ['intel-admin'], text: 'Read the laptop in the administration wing' }] },
      { id: 'free', title: 'Free Mara', objectives: [{ id: 'find', kind: 'find', text: 'Reach the building where she is held' }, { id: 'free', kind: 'free', text: 'Cut her loose' }] },
      { id: 'call', title: 'Call the helicopter', objectives: [{ id: 'call', kind: 'call', text: 'Use the radio at the north yard' }] },
      { id: 'hold', title: 'Hold the landing zone', objectives: [{ id: 'defend', kind: 'defend', text: 'Hold the north yard until the helicopter lands' }] },
      { id: 'out', title: 'Fly out', objectives: [{ id: 'escort', kind: 'escort', text: 'Get Mara to the helicopter' }, { id: 'extract', kind: 'extract', text: 'Everyone aboard' }] },
    ],
    par: { normal: 26 * 60, hard: 30 * 60, nightmare: 34 * 60 },
    tools: { pebbles: 5, charges: 2, drone: true },
  },
  {
    id: 'kennels', number: 3, name: 'The Kennels', estimate: '25 to 40 minutes', map: 'compound',
    briefing: 'Dr. Ilse Varga, a field medic, is held in the south barracks, and the guards have brought in dogs. Dogs smell you through walls: keep your distance, keep moving, or put them down quietly. A keycard opens the barracks. Walk her the long way east to the jeep.',
    spawns: ['south-field', 'southwest-corner'], cells: ['barracks-a', 'barracks-b', 'medical-hut', 'gatehouse'], hostages: 1, hostageName: 'Ilse',
    extraction: 'east-jeep',
    cameras: ['barracks-pole-camera', 'loading-pole-camera', 'admin-pole-camera', 'huts-pole-camera', 'annex-gate-camera', 'jeep-camera', 'detention-camera', 'security-camera'],
    panels: ['fuse-yard', 'intel-workshop', 'card-medical', 'card-shed', 'card-gatehouse', 'ammo-court', 'ammo-annex', 'medkit-south'],
    lockedDoors: [
      { door: 'South barracks A · entry 1', lock: 'keycard', card: 'barracks-card', label: 'barracks A' },
      { door: 'South barracks B · long wing · entry 1', lock: 'keycard', card: 'barracks-card', label: 'barracks B' },
      { door: 'East utility hut B · entry 1', lock: 'pick', label: 'the medical hut' },
      { door: 'Inner gatehouse · entry 1', lock: 'pick', label: 'the gatehouse' },
    ],
    keycards: [{ id: 'barracks-card', label: 'the barracks keycard', at: ['card-medical', 'card-shed', 'card-gatehouse'] }],
    boosts: ['inner-fence', 'rail-fence'],
    guards: ['world', 'reserve-extra-1', 'reserve-extra-2', 'reserve-extra-3', 'reserve-extra-4', 'south-yard-a', 'south-yard-b', 'barracks-a-inside', 'barracks-b-inside', 'huts-patrol', 'medical-inside', 'gatehouse-yard',
      'court-patrol', 'court-night', 'crew-yard', 'detention-yard', 'south-night', 'annex-night-2', 'warehouse-night'],
    dogs: ['dog-south-a', 'dog-south-b', 'dog-huts', 'dog-court', 'dog-annex'], alarmLocks: ['South barracks A · entry 1', 'South barracks B · long wing · entry 1'],
    stages: [
      { id: 'in', title: 'Into the south yard', objectives: [{ id: 'reach-south', kind: 'reach', zone: 'south-yard', text: 'Slip into the south yard past the dogs' }] },
      { id: 'card', title: 'The keycard', objectives: [{ id: 'card', kind: 'use', panels: ['card-medical', 'card-shed', 'card-gatehouse'], text: 'Find the barracks keycard (the laptop in the workshop says where)' },
        { id: 'intel', kind: 'use', panels: ['intel-workshop'], text: 'Read the laptop in the workshop', optional: true }] },
      { id: 'free', title: 'Free Ilse', objectives: [{ id: 'find', kind: 'find', text: 'Find the room she is held in' }, { id: 'free', kind: 'free', text: 'Cut her loose' }] },
      { id: 'power', title: 'Darken the east', objectives: [{ id: 'power', kind: 'use', panels: ['fuse-yard'], text: 'Cut the power by the loading lane to blind the annex cameras', optional: true }] },
      { id: 'escort', title: 'The long walk', objectives: [{ id: 'escort', kind: 'escort', text: 'Walk Ilse east to the jeep by the annex gate' }] },
      { id: 'out', title: 'Drive', objectives: [{ id: 'extract', kind: 'extract', text: 'Open the gate and drive out together' }] },
    ],
    par: { normal: 28 * 60, hard: 32 * 60, nightmare: 38 * 60 },
    tools: { pebbles: 6, charges: 1, drone: true },
  },
  {
    id: 'signal-fire', number: 4, name: 'Signal Fire', estimate: '30 to 40 minutes', map: 'compound',
    briefing: 'The team that went in last night is missing. Their radio operator, Petra Holm, is held in the east annex, and the camera net has doubled. Marksmen watch from the roofs: look for the glint. Kill the annex power, find her in the logbook, and hold the annex apron for the helicopter.',
    spawns: ['rail-siding', 'north-road'], cells: ['detention-2', 'detention-3', 'detention-4', 'warehouse-east'], hostages: 1, hostageName: 'Petra',
    extraction: 'annex-apron-heli',
    cameras: ['detention-camera', 'jeep-camera', 'security-camera', 'mess-hall-exit-camera', 'rail-pole-camera', 'annex-gate-camera', 'huts-pole-camera', 'yard-pole-camera'],
    panels: ['fuse-annex', 'intel-security', 'card-crew', 'card-mess', 'ammo-annex', 'ammo-yard', 'twokey-a', 'twokey-b'],
    lockedDoors: [
      { door: 'Security cabin · north door', lock: 'keycard', card: 'annex-card', label: 'the security cabin' },
      { door: 'Security cabin · south door', lock: 'pick', label: 'the security cabin' },
      { door: 'Detention entrance', lock: 'keycard', card: 'annex-card', label: 'the detention block' },
      { door: 'West administration wing · entry 1', lock: 'twokey', panel: 'twokey-a', label: 'the records room' },
    ],
    keycards: [{ id: 'annex-card', label: 'the annex keycard', at: ['card-crew', 'card-mess'] }],
    boosts: ['annex-fence', 'rail-fence', 'inner-fence'],
    guards: ['world', 'reserve-extra-1', 'reserve-extra-2', 'reserve-extra-3', 'reserve-extra-4', 'annex-rail-watch', 'detention-yard', 'annex-apron', 'security-inside', 'crew-yard', 'rail-yard-2', 'warehouse-stores', 'warehouse-rear',
      'mess-roof-sniper', 'maintenance-roof-sniper', 'annex-night-1', 'annex-night-2', 'yard-night', 'warehouse-night', 'court-night'],
    dogs: ['dog-annex', 'dog-yard'], alarmLocks: ['Detention entrance', 'Security cabin · north door', 'Crew house · north door'],
    stages: [
      { id: 'in', title: 'Reach the annex', objectives: [{ id: 'reach-annex', kind: 'reach', zone: 'annex', text: 'Get into the east annex unseen' }] },
      { id: 'dark', title: 'Kill the annex power', objectives: [{ id: 'power', kind: 'use', panels: ['fuse-annex'], text: 'Cut the power behind the maintenance shelter' }] },
      { id: 'intel', title: 'The logbook', objectives: [{ id: 'card', kind: 'use', panels: ['card-crew', 'card-mess'], text: 'Find the annex keycard (or pick the cabin lock)', optional: true },
        { id: 'intel', kind: 'use', panels: ['intel-security'], text: 'Read the logbook in the security cabin' }] },
      { id: 'free', title: 'Free Petra', objectives: [{ id: 'find', kind: 'find', text: 'Find where they are keeping her' }, { id: 'free', kind: 'free', text: 'Free her' }] },
      { id: 'call', title: 'Call the helicopter', objectives: [{ id: 'call', kind: 'call', text: 'Use the radio on the annex apron' }] },
      { id: 'hold', title: 'Hold the apron', objectives: [{ id: 'defend', kind: 'defend', text: 'Hold the apron until the helicopter lands' }] },
      { id: 'out', title: 'Fly out', objectives: [{ id: 'escort', kind: 'escort', text: 'Get Petra to the helicopter' }, { id: 'extract', kind: 'extract', text: 'Everyone aboard' }] },
    ],
    par: { normal: 30 * 60, hard: 35 * 60, nightmare: 40 * 60 },
    tools: { pebbles: 5, charges: 2, drone: true },
  },
  {
    id: 'last-light', number: 5, name: 'Last Light', estimate: '35 to 45 minutes', map: 'compound',
    briefing: 'Two prisoners, held apart: Nell Vell, Tomas\'s daughter, and Arno, the compound mechanic who helped us. The garrison is on full alert, and the alarm locks the doors. Free both and bring them to the loading court together. Only a two-key panel opens the records room with the prisoner list.',
    spawns: ['southwest-corner', 'fuel-belt', 'rail-siding'], cells: ['stores-southwest', 'shed-southwest', 'medical-hut', 'detention-1', 'barracks-b', 'admin'], hostages: 2, hostageName: 'Nell and Arno',
    extraction: 'loading-court-heli',
    cameras: ['mess-hall-exit-camera', 'yard-pole-camera', 'loading-pole-camera', 'barracks-pole-camera', 'admin-pole-camera', 'stores-pole-camera', 'huts-pole-camera',
      'rail-pole-camera', 'annex-gate-camera', 'west-shed-camera', 'detention-camera', 'jeep-camera', 'security-camera'],
    panels: ['fuse-west', 'fuse-annex', 'twokey-a', 'twokey-b', 'intel-admin', 'card-gatehouse', 'card-medical', 'card-crew', 'ammo-yard', 'ammo-court', 'ammo-annex', 'medkit-south', 'medkit-west'],
    lockedDoors: [
      { door: 'West administration wing · entry 1', lock: 'twokey', panel: 'twokey-a', label: 'the records room' },
      { door: 'Southwest stores · entry 2', lock: 'keycard', card: 'master-card', label: 'the stores' },
      { door: 'Southwest service shed · entry 1', lock: 'pick', label: 'the service shed' },
      { door: 'East utility hut B · entry 1', lock: 'pick', label: 'the medical hut' },
      { door: 'South barracks B · long wing · entry 1', lock: 'keycard', card: 'master-card', label: 'barracks B' },
      { door: 'Detention entrance', lock: 'keycard', card: 'master-card', label: 'the detention block' },
    ],
    keycards: [{ id: 'master-card', label: 'the master keycard', at: ['card-gatehouse', 'card-medical', 'card-crew'] }],
    boosts: ['rail-fence', 'annex-fence', 'inner-fence'],
    guards: ['world', 'reserve-extra-1', 'reserve-extra-2', 'reserve-extra-3', 'reserve-extra-4', 'stores-yard', 'stores-inside', 'shed-watch', 'west-fence', 'gatehouse-yard', 'admin-inside', 'south-yard-a', 'south-yard-b', 'barracks-b-inside',
      'huts-patrol', 'medical-inside', 'court-patrol', 'court-night', 'detention-yard', 'annex-rail-watch', 'crew-yard', 'mess-roof-sniper', 'maintenance-roof-sniper',
      'south-night', 'west-night', 'yard-night', 'warehouse-night', 'annex-night-1'],
    dogs: ['dog-south-a', 'dog-south-b', 'dog-stores', 'dog-huts', 'dog-court', 'dog-yard'],
    alarmLocks: ['Southwest stores · entry 2', 'South barracks B · long wing · entry 1', 'Detention entrance', 'East utility hut B · entry 1', 'Inner gatehouse · entry 1'],
    stages: [
      { id: 'dark', title: 'Blackout', objectives: [{ id: 'power-west', kind: 'use', panels: ['fuse-west'], text: 'Cut the west power' }, { id: 'power-east', kind: 'use', panels: ['fuse-annex'], text: 'Cut the annex power', optional: true }] },
      { id: 'list', title: 'The prisoner list', objectives: [{ id: 'intel', kind: 'use', panels: ['intel-admin'], text: 'Open the records room (two keys at once, or pick it) and read the list' }] },
      { id: 'card', title: 'The master key', objectives: [{ id: 'card', kind: 'use', panels: ['card-gatehouse', 'card-medical', 'card-crew'], text: 'Take the master keycard' }] },
      { id: 'free', title: 'Free them both', objectives: [{ id: 'find', kind: 'find', text: 'Find Nell and Arno' }, { id: 'free', kind: 'free', text: 'Free them both' }] },
      { id: 'call', title: 'Call the helicopter', objectives: [{ id: 'call', kind: 'call', text: 'Use the radio at the loading court' }] },
      { id: 'hold', title: 'Last stand', objectives: [{ id: 'defend', kind: 'defend', text: 'Hold the loading court until the helicopter lands' }] },
      { id: 'out', title: 'Home', objectives: [{ id: 'escort', kind: 'escort', text: 'Get them both aboard' }, { id: 'extract', kind: 'extract', text: 'Everyone aboard' }] },
    ],
    par: { normal: 34 * 60, hard: 40 * 60, nightmare: 46 * 60 },
    tools: { pebbles: 6, charges: 3, drone: true },
  },
]

export const missionById = (id: string | null | undefined) => MISSIONS.find(mission => mission.id === id)
export const mapFor = (mission: MissionDef) => MAPS[mission.map] ?? COMPOUND_MAP
export const MISSION_IDS = MISSIONS.map(mission => mission.id)
