// Solve every gun's grip (grips.ts) and write them to src/game/grip-plans.ts, so taking up a gun in the game
// costs nothing. Run after changing a gun's model or the grip solver:
//   node scripts/check-player.mjs scripts/bake-grips.ts
import { writeFileSync } from 'node:fs'
import { bakeGrip, gripKey, solveGripPlan } from '../src/game/grips'
import { GRIP_GUNS } from './grip-guns'
import { createMissionGun } from '../src/game/weapon-models'

const lines: string[] = []
for (const item of GRIP_GUNS) {
  const model = createMissionGun(item.name, item.special)
  const key = gripKey(item, model)
  lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(bakeGrip(solveGripPlan(model as never, item, key)))},`)
}
writeFileSync('src/game/grip-plans.ts', `// Generated by scripts/bake-grips.ts: every gun's solved grip (grips.ts). Do not edit; re-run the script.
export type BakedGrip = {
  firing: number[]
  support: number[]
  idle: BakedPose
  pull: BakedPose
  supportPose: BakedPose
  style: 'cup' | 'handguard' | 'vertical' | 'tank'
}
type BakedPose = { fingers: { curl: number[]; spread: number }[]; thumb: { yaw: number; lift: number; curl: number[]; twist: number } }

export const BAKED_GRIPS: Record<string, BakedGrip> = {
${lines.join('\n')}
}
`)
console.log(`Baked ${lines.length} grips.`)
